apiVersion: apps/v1
kind: Deployment
metadata:
  name: sergio-demo-sa
  namespace: golo-sa
  labels:
    app: sergio-demo-sa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sergio-demo-sa
  template:
    metadata:
      labels:
        app: sergio-demo-sa
    spec:
      containers:
        - name: sergio-demo-sa
          image: crmultitenant.azurecr.io/sergio/demo:2.0.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: sergio-demo-sa
  namespace: golo-sa
spec:
  selector:
    app: sergio-demo-sa
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP