apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sergio-demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/gt"
            backend:
              service:
                name: sergio-demo-gt
                port:
                  number: 8080
              namespace: golo-gt
          - pathType: Prefix
            path: "/sa"
            backend:
              service:
                name: sergio-demo-sa
                port:
                  number: 8080
              namespace: golo-sa

