apiVersion: apps/v1
kind: Deployment
metadata:
  name: sergio-demo
  namespace: golo-sa
  labels:
    app: sergio-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sergio-demo
  template:
    metadata:
      labels:
        app: sergio-demo
    spec:
      containers:
        - name: sergio-demo
          image: crmultitenant.azurecr.io/sergio/demo:5.0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 300m
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: sergio-demo
  namespace: golo-sa
spec:
  selector:
    app: sergio-demo
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP